### ISSUE TITLE
GBA Mode 3 Sprite Export gives unexpected results

### ISSUE THREAD

**Issue by ahirschberg** [TricksterGuy/nin10kit#15]
How to reproduce the issue:
1. From `nin10kitgui` select GBA Sprites (Mode 3) - 4 Bpp Sprites, and keep the image size at the default (8x32 for my image)
I'm using [this image](https://github.com/ahirschberg/cool_game_gba/blob/94e1cbb01976a4b9d259d67b7b62f8e18921e0c0/assets/projectile_sprites.png) as the example, since it's relatively simple and used in my game. It's four 8x8 frames of a white-colored dot.
2. For comparison, I also export using [coranc's grit utility](http://www.coranac.com/projects/#grit) with the command (on my machine) 
`wine ~/Downloads/grit/grit.exe assets/projectile_sprites.png -gB4 -Mh 1 -Mw 1 -ftc`.
The command line flags set 4bpp colors, a sprite size of 8x8 (1 tile), and an output filetype of `.c`, respectively.

I don't know enough about how nin10kit(gui) works internally to understand exactly what nin10kit is giving me, but it doesn't match up with grit's output and also doesn't seem to display in game. It may be an issue with the gui specifically, but I don't know how to get mode 3 sprites from `nin10kit` on command line.

Here is the [grit export file](https://gist.github.com/ahirschberg/2b3f5732047a683ce111e3018156b558#file-projectile_sprites_grit-c-L17-L23) and [nin10kit export file](https://gist.github.com/ahirschberg/2b3f5732047a683ce111e3018156b558#file-nin10kitprojectile-c-L53-L63) I am getting, for comparison. Notice that nin10kit seems to export all `0x0`s for the tiles, while grit exports actual data. I am able to get this to show up in my game in mode 3 with the grit export:
![screenshot2016-12-2019 39 41](https://cloud.githubusercontent.com/assets/5578698/21373334/20d4408e-c6ec-11e6-9f59-efc6a80e4362.png)

**Comment by TricksterGuy** [comment]
command line equivalent: 

nin10kit -mode=sprites -for_bitmap=1 -bpp=4 projectile_sprites projectile_sprites.png 

This appears to already be fixed in @f1cfe95a09649adcff61b73562fd3a36e4f91113

Interesting enough is why is the color being picked 0x7dfe instead of 0x7fff?

**Comment by ahirschberg** [comment]
Here is the projectile_sprites.png as I see it in GIMP:
![screenshot2016-12-2223 14 48](https://cloud.githubusercontent.com/assets/5578698/21447067/cf6470ae-c89c-11e6-8794-1d3e066c374f.png) (wish that image wasn't so big...)

I then ran `nin10kit -mode=sprites -for_bitmap=1 -bpp=4 nin10kitprojectile assets/projectile_sprites.png`
Exporting with this command gives me the following for projectiles in game (after updating the projectile asset loading in main.c):
![screenshot2016-12-2223 12 22](https://cloud.githubusercontent.com/assets/5578698/21447031/2995c1d2-c89c-11e6-9f49-69da2d6c7573.png)

[nin10kitprojectile.c output from that command](https://github.com/ahirschberg/cool_game_gba/commit/5a925eabb6e6dd26132cbf5c89eb99c6f151d896#diff-47b443bf6265d47748b6dbabae3ffa8cR53)

**Comment by TricksterGuy** [comment]
Yeah its not obeying transparent pixels.  My code did not discard completely transparent pixels, it just discarded the alpha value originally.  Meaning whatever color those transparent pixels were will appear in the output incorrectly.

As I said above, Its already fixed, if you recompile from the repo or patch in the changes in f1cfe95a09649adcff61b73562fd3a36e4f91113  Its only 4 modified lines.

Here is the output.  https://gist.github.com/TricksterGuy/3a51b839d14c88906ae24288a45afbd4


Otherwise, you can open your image in gimp.  Recolor the projectiles temporarily.  Remove the alpha channel.  Recolor the background. Recolor the projectiles back to white.  Add Alpha channel.  Convert the background back to transparency and save.
