### ISSUE TITLE
Support for arbitrary animation sizes

### ISSUE THREAD

**Issue by HorstBaerbel** [TricksterGuy/nin10kit#31]
I have a 24 frame 128x64 animation with 16 colors (either 24 PNGs or one GIF). I will load different chunks of it into tiles and then use them in mode 0/1. The problem is that --mode=tiles ("F[16:37:30.916]Too many tiles. Found 2075 tiles. Please make the image simpler.") and sprites ("W[16:37:50.809]Invalid sprite size for image anim, (128 64). Note that only a tile-id offset will be emitted.") do not work here, and --mode=4 exports 256-color data.
How can I convert my animation (--force does not work)?

**Comment by TricksterGuy** [comment]
Yeah I should go throughout the codebase and find instances where the program would exit due to an error.  --force was a last minute thing I added and forgot to have it just ignore everything else.

**Comment by TricksterGuy** [comment]
With commit  bced16f8074dcc139ddc8a7f51727a73c7c0ab34 that should be all of them.

**Comment by HorstBaerbel** [comment]
Export works now with --force. Thanks!
